name: app_test1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_modular: ^6.0.4+1
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  flutter_native_splash: ^2.3.2
  lottie: ^2.6.0
  intl: ^0.19.0
  extended_masked_text: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
